export enum LogName {
  UserCreated = 'user.created',
  UserUpdated = 'user.updated',
  UserDeleted = 'user.deleted',
  UserValidated = 'user.validated',
  UserExtraDataCreated = 'userExtraData.created',
  UserExtraDataUpdated = 'userExtraData.updated',
  UserExtraDataDeleted = 'userExtraData.deleted',
  SubmissionCreated = 'submission.created',
  SubmissionSubmitted = 'submission.submitted',
  SubmissionUnsubmitted = 'submission.unsubmitted',
  PaperCreated = 'paper.created',
  PaperUpdated = 'paper.updated',
  PaperDeleted = 'paper.deleted',
  PaperValidated = 'paper.validated',
  PaperInvalidated = 'paper.invalidated',
  PaperCancelledValidation = 'paper.cancelledValidation',
  PaperAssigned = 'paper.assigned',
  PaperUnassigned = 'paper.unassigned',
  PaperGraded = 'paper.graded',
  DocumentCreated = 'document.created',
  DocumentContentUpdated = 'document.contentUpdated',
  DocumentDeleted = 'document.deleted',
  DocumentReuploadRequestCreated = 'documentReuploadRequest.created',
  DocumentReuploadRequestDeleted = 'documentReuploadRequest.deleted',
}