import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1770589825379 implements MigrationInterface {
    name = 'InitSchema1770589825379'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`topic\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_15f634a2dbf62a79bb726fc615\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`application\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` varchar(1024) NOT NULL, \`usedTechnologies\` varchar(255) NULL, \`accepted\` tinyint NULL, \`offerId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`studentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offer\` (\`id\` int NOT NULL AUTO_INCREMENT, \`description\` varchar(1024) NULL, \`limit\` int NOT NULL, \`takenSeats\` int NOT NULL DEFAULT '0', \`teacherId\` int NULL, \`domainId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`domain\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`type\` enum ('bachelor', 'master') NOT NULL, \`paperType\` enum ('bachelor', 'diploma', 'master') NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`specialization\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`studyYears\` int NOT NULL, \`studyForm\` enum ('if', 'ifr', 'id') NOT NULL, \`domainId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`profile\` (\`id\` int NOT NULL AUTO_INCREMENT, \`bio\` varchar(255) NULL, \`website\` varchar(255) NULL, \`picture\` varchar(255) NULL, \`userId\` int NULL, UNIQUE INDEX \`REL_a24972ebd73b106250713dcddd\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`category\` varchar(255) NOT NULL, \`type\` enum ('generated', 'signed', 'copy') NOT NULL, \`mimeType\` varchar(255) NOT NULL, \`meta\` text NOT NULL, \`uploadedById\` int NULL, \`paperId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`committee_activity_day\` (\`id\` int NOT NULL AUTO_INCREMENT, \`location\` varchar(255) NOT NULL, \`startTime\` datetime NOT NULL, \`committeeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`committee\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`paperPresentationTime\` int NOT NULL DEFAULT '15', \`publicScheduling\` tinyint NOT NULL DEFAULT 0, \`finalGrades\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`committee_member\` (\`committeeId\` int NOT NULL, \`teacherId\` int NOT NULL, \`role\` enum ('president', 'secretary', 'member') NOT NULL, PRIMARY KEY (\`committeeId\`, \`teacherId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`paper_grade\` (\`committeeMemberCommitteeId\` int NOT NULL, \`committeeMemberTeacherId\` int NOT NULL, \`paperId\` int NOT NULL, \`forPaper\` int NOT NULL, \`forPresentation\` int NOT NULL, PRIMARY KEY (\`committeeMemberCommitteeId\`, \`committeeMemberTeacherId\`, \`paperId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`submission\` (\`id\` int NOT NULL AUTO_INCREMENT, \`submittedAt\` datetime NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_reupload_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`documentName\` varchar(255) NOT NULL, \`comment\` varchar(255) NULL, \`deadline\` datetime NOT NULL, \`paperId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`paper\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` varchar(1024) NOT NULL, \`type\` enum ('bachelor', 'diploma', 'master') NOT NULL, \`isValid\` tinyint NULL, \`scheduledGrading\` datetime NULL, \`studentId\` int NOT NULL, \`teacherId\` int NULL, \`committeeId\` int NULL, \`submissionId\` int NULL, \`requiredDocuments\` text NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, INDEX \`IDX_a42a1dc5780fb4a26ab4f9e775\` (\`studentId\`), UNIQUE INDEX \`REL_f73f1247307fd847021d2e88dc\` (\`submissionId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`address\` (\`id\` int NOT NULL AUTO_INCREMENT, \`country\` varchar(255) NOT NULL, \`county\` varchar(255) NOT NULL, \`locality\` varchar(255) NOT NULL, \`street\` varchar(255) NOT NULL, \`streetNumber\` varchar(255) NOT NULL, \`building\` varchar(255) NULL, \`stair\` varchar(255) NULL, \`floor\` varchar(255) NULL, \`apartment\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_extra_data\` (\`userId\` int NOT NULL, \`birthLastName\` varchar(255) NOT NULL, \`parentInitial\` varchar(255) NOT NULL, \`fatherName\` varchar(255) NOT NULL, \`motherName\` varchar(255) NOT NULL, \`civilState\` enum ('not_married', 'married', 'divorced', 'widow', 're_married') NOT NULL, \`dateOfBirth\` date NOT NULL, \`citizenship\` varchar(255) NOT NULL, \`ethnicity\` varchar(255) NOT NULL, \`placeOfBirthCountry\` varchar(255) NOT NULL, \`placeOfBirthCounty\` varchar(255) NOT NULL, \`placeOfBirthLocality\` varchar(255) NOT NULL, \`landline\` varchar(255) NOT NULL, \`mobilePhone\` varchar(255) NOT NULL, \`personalEmail\` varchar(255) NOT NULL, \`addressId\` int NULL, UNIQUE INDEX \`REL_a5230462e15d6d2036a51cabd2\` (\`addressId\`), PRIMARY KEY (\`userId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` varchar(255) NOT NULL, \`firstName\` varchar(255) NOT NULL, \`lastName\` varchar(255) NOT NULL, \`title\` varchar(255) NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NULL, \`CNP\` varchar(255) NULL, \`validated\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`group\` varchar(255) NULL, \`promotion\` varchar(255) NULL, \`identificationCode\` varchar(255) NULL, \`matriculationYear\` varchar(255) NULL, \`fundingForm\` enum ('budget', 'tax') NULL, \`generalAverage\` float NULL, \`specializationId\` int NULL, INDEX \`IDX_31ef2b4d30675d0c15056b7f6e\` (\`type\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sign_up_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`firstName\` varchar(255) NOT NULL, \`lastName\` varchar(255) NOT NULL, \`CNP\` varchar(255) NULL, \`email\` varchar(255) NOT NULL, \`identificationCode\` varchar(255) NOT NULL, \`matriculationYear\` varchar(255) NOT NULL, \`promotion\` varchar(255) NOT NULL, \`group\` varchar(255) NOT NULL, \`fundingForm\` enum ('budget', 'tax') NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`specializationId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`activation_token\` (\`id\` int NOT NULL AUTO_INCREMENT, \`token\` varchar(255) NOT NULL, \`userId\` int NOT NULL, \`used\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_03cb360d6466a6206a6e731eda\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`signature\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`session_settings\` (\`id\` int NOT NULL DEFAULT '1', \`sessionName\` varchar(255) NOT NULL, \`currentPromotion\` varchar(255) NOT NULL, \`applyStartDate\` datetime NOT NULL, \`applyEndDate\` datetime NOT NULL, \`fileSubmissionStartDate\` datetime NOT NULL, \`fileSubmissionEndDate\` datetime NOT NULL, \`paperSubmissionEndDate\` datetime NOT NULL, \`allowGrading\` tinyint NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`log\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`severity\` enum ('info', 'warning', 'error', 'critical') NOT NULL, \`timestamp\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`meta\` json NULL, \`byUserId\` int NULL, \`impersonatedByUserId\` int NULL, \`userId\` int NULL, \`userExtraDataId\` int NULL, \`paperId\` int NULL, \`documentId\` int NULL, \`documentReuploadRequestId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offer_topics\` (\`offerId\` int NOT NULL, \`topicId\` int NOT NULL, INDEX \`IDX_9bb0af9b64e26280893e096649\` (\`offerId\`), INDEX \`IDX_a46b1ba1b64837c6252a579457\` (\`topicId\`), PRIMARY KEY (\`offerId\`, \`topicId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`committee_domains\` (\`committeeId\` int NOT NULL, \`domainId\` int NOT NULL, INDEX \`IDX_17017bc997af765d386bd31ce1\` (\`committeeId\`), INDEX \`IDX_951efb09baa40c6569827bb6c5\` (\`domainId\`), PRIMARY KEY (\`committeeId\`, \`domainId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`paper_topics\` (\`paperId\` int NOT NULL, \`topicId\` int NOT NULL, INDEX \`IDX_aa4976fac972b37ab420c50b62\` (\`paperId\`), INDEX \`IDX_e4ad00c6142fdd67d2f2297344\` (\`topicId\`), PRIMARY KEY (\`paperId\`, \`topicId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`student_topics\` (\`userId\` int NOT NULL, \`topicId\` int NOT NULL, INDEX \`IDX_35599d1d3ad61a3c680fea7e36\` (\`userId\`), INDEX \`IDX_118bbf29c0689ae3c897a5f38b\` (\`topicId\`), PRIMARY KEY (\`userId\`, \`topicId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`application\` ADD CONSTRAINT \`FK_85f13deb7bf2a0c3a39827de06e\` FOREIGN KEY (\`offerId\`) REFERENCES \`offer\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`application\` ADD CONSTRAINT \`FK_8bd9711f01c7ba0d0a26710f23b\` FOREIGN KEY (\`studentId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offer\` ADD CONSTRAINT \`FK_8c71e2de9fae7ec3d0e9a101eb6\` FOREIGN KEY (\`teacherId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offer\` ADD CONSTRAINT \`FK_d14b297a13f39cf80fa93b4a4ca\` FOREIGN KEY (\`domainId\`) REFERENCES \`domain\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`specialization\` ADD CONSTRAINT \`FK_125bdc304cfe83ab8375553f181\` FOREIGN KEY (\`domainId\`) REFERENCES \`domain\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD CONSTRAINT \`FK_a24972ebd73b106250713dcddd9\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document\` ADD CONSTRAINT \`FK_dce23e34ec9476f33a2ae621fb0\` FOREIGN KEY (\`paperId\`) REFERENCES \`paper\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document\` ADD CONSTRAINT \`FK_efb7e46d33872b088a2014d7975\` FOREIGN KEY (\`uploadedById\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`committee_activity_day\` ADD CONSTRAINT \`FK_6efcaea3c03d396ad99f8acd2bf\` FOREIGN KEY (\`committeeId\`) REFERENCES \`committee\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`committee_member\` ADD CONSTRAINT \`FK_d5394bf15be712347beb12c11ec\` FOREIGN KEY (\`committeeId\`) REFERENCES \`committee\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`committee_member\` ADD CONSTRAINT \`FK_00f2ee69ff4f91e0216bb51d1b0\` FOREIGN KEY (\`teacherId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`paper_grade\` ADD CONSTRAINT \`FK_95907787a9d3605eb8f25c6036f\` FOREIGN KEY (\`committeeMemberCommitteeId\`, \`committeeMemberTeacherId\`) REFERENCES \`committee_member\`(\`committeeId\`,\`teacherId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`paper_grade\` ADD CONSTRAINT \`FK_b0db3b9803b0a5b2f794847fe6d\` FOREIGN KEY (\`paperId\`) REFERENCES \`paper\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_reupload_request\` ADD CONSTRAINT \`FK_f0c356a087bb8ade4ac5cd69b36\` FOREIGN KEY (\`paperId\`) REFERENCES \`paper\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`paper\` ADD CONSTRAINT \`FK_f73f1247307fd847021d2e88dc7\` FOREIGN KEY (\`submissionId\`) REFERENCES \`submission\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`paper\` ADD CONSTRAINT \`FK_17d96e51ee61725e0cc91204ef7\` FOREIGN KEY (\`teacherId\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`paper\` ADD CONSTRAINT \`FK_ece1e1a59b4f74d14bdc094396a\` FOREIGN KEY (\`committeeId\`) REFERENCES \`committee\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_extra_data\` ADD CONSTRAINT \`FK_01bf3ae1c2035a7a70aab3befbb\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_extra_data\` ADD CONSTRAINT \`FK_a5230462e15d6d2036a51cabd2f\` FOREIGN KEY (\`addressId\`) REFERENCES \`address\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_6ee629b045554dc0b30beaa6c09\` FOREIGN KEY (\`specializationId\`) REFERENCES \`specialization\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sign_up_request\` ADD CONSTRAINT \`FK_f9a72a424da73135dba57088895\` FOREIGN KEY (\`specializationId\`) REFERENCES \`specialization\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activation_token\` ADD CONSTRAINT \`FK_868ff6bf50e1490b68d985ed008\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`signature\` ADD CONSTRAINT \`FK_7300eb2628d8e5139f1f109f7eb\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`log\` ADD CONSTRAINT \`FK_ba7a581f00fc1047a742c9ef206\` FOREIGN KEY (\`byUserId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`log\` ADD CONSTRAINT \`FK_f57b65b91616cd678ae9873a57a\` FOREIGN KEY (\`impersonatedByUserId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`log\` ADD CONSTRAINT \`FK_cea2ed3a494729d4b21edbd2983\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`log\` ADD CONSTRAINT \`FK_4010ac7535f24e58de115a17322\` FOREIGN KEY (\`userExtraDataId\`) REFERENCES \`user_extra_data\`(\`userId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`log\` ADD CONSTRAINT \`FK_a61e9988c2cb66054e45ba0a2d6\` FOREIGN KEY (\`paperId\`) REFERENCES \`paper\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`log\` ADD CONSTRAINT \`FK_934f0116583d1341a75f319e7c2\` FOREIGN KEY (\`documentId\`) REFERENCES \`document\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`log\` ADD CONSTRAINT \`FK_764a18bcc0d88a0dc53d0136fdc\` FOREIGN KEY (\`documentReuploadRequestId\`) REFERENCES \`document_reupload_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offer_topics\` ADD CONSTRAINT \`FK_9bb0af9b64e26280893e0966490\` FOREIGN KEY (\`offerId\`) REFERENCES \`offer\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offer_topics\` ADD CONSTRAINT \`FK_a46b1ba1b64837c6252a579457b\` FOREIGN KEY (\`topicId\`) REFERENCES \`topic\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`committee_domains\` ADD CONSTRAINT \`FK_17017bc997af765d386bd31ce17\` FOREIGN KEY (\`committeeId\`) REFERENCES \`committee\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`committee_domains\` ADD CONSTRAINT \`FK_951efb09baa40c6569827bb6c52\` FOREIGN KEY (\`domainId\`) REFERENCES \`domain\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`paper_topics\` ADD CONSTRAINT \`FK_aa4976fac972b37ab420c50b62a\` FOREIGN KEY (\`paperId\`) REFERENCES \`paper\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`paper_topics\` ADD CONSTRAINT \`FK_e4ad00c6142fdd67d2f2297344a\` FOREIGN KEY (\`topicId\`) REFERENCES \`topic\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`student_topics\` ADD CONSTRAINT \`FK_35599d1d3ad61a3c680fea7e365\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`student_topics\` ADD CONSTRAINT \`FK_118bbf29c0689ae3c897a5f38bf\` FOREIGN KEY (\`topicId\`) REFERENCES \`topic\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`student_topics\` DROP FOREIGN KEY \`FK_118bbf29c0689ae3c897a5f38bf\``);
        await queryRunner.query(`ALTER TABLE \`student_topics\` DROP FOREIGN KEY \`FK_35599d1d3ad61a3c680fea7e365\``);
        await queryRunner.query(`ALTER TABLE \`paper_topics\` DROP FOREIGN KEY \`FK_e4ad00c6142fdd67d2f2297344a\``);
        await queryRunner.query(`ALTER TABLE \`paper_topics\` DROP FOREIGN KEY \`FK_aa4976fac972b37ab420c50b62a\``);
        await queryRunner.query(`ALTER TABLE \`committee_domains\` DROP FOREIGN KEY \`FK_951efb09baa40c6569827bb6c52\``);
        await queryRunner.query(`ALTER TABLE \`committee_domains\` DROP FOREIGN KEY \`FK_17017bc997af765d386bd31ce17\``);
        await queryRunner.query(`ALTER TABLE \`offer_topics\` DROP FOREIGN KEY \`FK_a46b1ba1b64837c6252a579457b\``);
        await queryRunner.query(`ALTER TABLE \`offer_topics\` DROP FOREIGN KEY \`FK_9bb0af9b64e26280893e0966490\``);
        await queryRunner.query(`ALTER TABLE \`log\` DROP FOREIGN KEY \`FK_764a18bcc0d88a0dc53d0136fdc\``);
        await queryRunner.query(`ALTER TABLE \`log\` DROP FOREIGN KEY \`FK_934f0116583d1341a75f319e7c2\``);
        await queryRunner.query(`ALTER TABLE \`log\` DROP FOREIGN KEY \`FK_a61e9988c2cb66054e45ba0a2d6\``);
        await queryRunner.query(`ALTER TABLE \`log\` DROP FOREIGN KEY \`FK_4010ac7535f24e58de115a17322\``);
        await queryRunner.query(`ALTER TABLE \`log\` DROP FOREIGN KEY \`FK_cea2ed3a494729d4b21edbd2983\``);
        await queryRunner.query(`ALTER TABLE \`log\` DROP FOREIGN KEY \`FK_f57b65b91616cd678ae9873a57a\``);
        await queryRunner.query(`ALTER TABLE \`log\` DROP FOREIGN KEY \`FK_ba7a581f00fc1047a742c9ef206\``);
        await queryRunner.query(`ALTER TABLE \`signature\` DROP FOREIGN KEY \`FK_7300eb2628d8e5139f1f109f7eb\``);
        await queryRunner.query(`ALTER TABLE \`activation_token\` DROP FOREIGN KEY \`FK_868ff6bf50e1490b68d985ed008\``);
        await queryRunner.query(`ALTER TABLE \`sign_up_request\` DROP FOREIGN KEY \`FK_f9a72a424da73135dba57088895\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_6ee629b045554dc0b30beaa6c09\``);
        await queryRunner.query(`ALTER TABLE \`user_extra_data\` DROP FOREIGN KEY \`FK_a5230462e15d6d2036a51cabd2f\``);
        await queryRunner.query(`ALTER TABLE \`user_extra_data\` DROP FOREIGN KEY \`FK_01bf3ae1c2035a7a70aab3befbb\``);
        await queryRunner.query(`ALTER TABLE \`paper\` DROP FOREIGN KEY \`FK_ece1e1a59b4f74d14bdc094396a\``);
        await queryRunner.query(`ALTER TABLE \`paper\` DROP FOREIGN KEY \`FK_17d96e51ee61725e0cc91204ef7\``);
        await queryRunner.query(`ALTER TABLE \`paper\` DROP FOREIGN KEY \`FK_f73f1247307fd847021d2e88dc7\``);
        await queryRunner.query(`ALTER TABLE \`document_reupload_request\` DROP FOREIGN KEY \`FK_f0c356a087bb8ade4ac5cd69b36\``);
        await queryRunner.query(`ALTER TABLE \`paper_grade\` DROP FOREIGN KEY \`FK_b0db3b9803b0a5b2f794847fe6d\``);
        await queryRunner.query(`ALTER TABLE \`paper_grade\` DROP FOREIGN KEY \`FK_95907787a9d3605eb8f25c6036f\``);
        await queryRunner.query(`ALTER TABLE \`committee_member\` DROP FOREIGN KEY \`FK_00f2ee69ff4f91e0216bb51d1b0\``);
        await queryRunner.query(`ALTER TABLE \`committee_member\` DROP FOREIGN KEY \`FK_d5394bf15be712347beb12c11ec\``);
        await queryRunner.query(`ALTER TABLE \`committee_activity_day\` DROP FOREIGN KEY \`FK_6efcaea3c03d396ad99f8acd2bf\``);
        await queryRunner.query(`ALTER TABLE \`document\` DROP FOREIGN KEY \`FK_efb7e46d33872b088a2014d7975\``);
        await queryRunner.query(`ALTER TABLE \`document\` DROP FOREIGN KEY \`FK_dce23e34ec9476f33a2ae621fb0\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP FOREIGN KEY \`FK_a24972ebd73b106250713dcddd9\``);
        await queryRunner.query(`ALTER TABLE \`specialization\` DROP FOREIGN KEY \`FK_125bdc304cfe83ab8375553f181\``);
        await queryRunner.query(`ALTER TABLE \`offer\` DROP FOREIGN KEY \`FK_d14b297a13f39cf80fa93b4a4ca\``);
        await queryRunner.query(`ALTER TABLE \`offer\` DROP FOREIGN KEY \`FK_8c71e2de9fae7ec3d0e9a101eb6\``);
        await queryRunner.query(`ALTER TABLE \`application\` DROP FOREIGN KEY \`FK_8bd9711f01c7ba0d0a26710f23b\``);
        await queryRunner.query(`ALTER TABLE \`application\` DROP FOREIGN KEY \`FK_85f13deb7bf2a0c3a39827de06e\``);
        await queryRunner.query(`DROP INDEX \`IDX_118bbf29c0689ae3c897a5f38b\` ON \`student_topics\``);
        await queryRunner.query(`DROP INDEX \`IDX_35599d1d3ad61a3c680fea7e36\` ON \`student_topics\``);
        await queryRunner.query(`DROP TABLE \`student_topics\``);
        await queryRunner.query(`DROP INDEX \`IDX_e4ad00c6142fdd67d2f2297344\` ON \`paper_topics\``);
        await queryRunner.query(`DROP INDEX \`IDX_aa4976fac972b37ab420c50b62\` ON \`paper_topics\``);
        await queryRunner.query(`DROP TABLE \`paper_topics\``);
        await queryRunner.query(`DROP INDEX \`IDX_951efb09baa40c6569827bb6c5\` ON \`committee_domains\``);
        await queryRunner.query(`DROP INDEX \`IDX_17017bc997af765d386bd31ce1\` ON \`committee_domains\``);
        await queryRunner.query(`DROP TABLE \`committee_domains\``);
        await queryRunner.query(`DROP INDEX \`IDX_a46b1ba1b64837c6252a579457\` ON \`offer_topics\``);
        await queryRunner.query(`DROP INDEX \`IDX_9bb0af9b64e26280893e096649\` ON \`offer_topics\``);
        await queryRunner.query(`DROP TABLE \`offer_topics\``);
        await queryRunner.query(`DROP TABLE \`log\``);
        await queryRunner.query(`DROP TABLE \`session_settings\``);
        await queryRunner.query(`DROP TABLE \`signature\``);
        await queryRunner.query(`DROP INDEX \`IDX_03cb360d6466a6206a6e731eda\` ON \`activation_token\``);
        await queryRunner.query(`DROP TABLE \`activation_token\``);
        await queryRunner.query(`DROP TABLE \`sign_up_request\``);
        await queryRunner.query(`DROP INDEX \`IDX_31ef2b4d30675d0c15056b7f6e\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP INDEX \`REL_a5230462e15d6d2036a51cabd2\` ON \`user_extra_data\``);
        await queryRunner.query(`DROP TABLE \`user_extra_data\``);
        await queryRunner.query(`DROP TABLE \`address\``);
        await queryRunner.query(`DROP INDEX \`REL_f73f1247307fd847021d2e88dc\` ON \`paper\``);
        await queryRunner.query(`DROP INDEX \`IDX_a42a1dc5780fb4a26ab4f9e775\` ON \`paper\``);
        await queryRunner.query(`DROP TABLE \`paper\``);
        await queryRunner.query(`DROP TABLE \`document_reupload_request\``);
        await queryRunner.query(`DROP TABLE \`submission\``);
        await queryRunner.query(`DROP TABLE \`paper_grade\``);
        await queryRunner.query(`DROP TABLE \`committee_member\``);
        await queryRunner.query(`DROP TABLE \`committee\``);
        await queryRunner.query(`DROP TABLE \`committee_activity_day\``);
        await queryRunner.query(`DROP TABLE \`document\``);
        await queryRunner.query(`DROP INDEX \`REL_a24972ebd73b106250713dcddd\` ON \`profile\``);
        await queryRunner.query(`DROP TABLE \`profile\``);
        await queryRunner.query(`DROP TABLE \`specialization\``);
        await queryRunner.query(`DROP TABLE \`domain\``);
        await queryRunner.query(`DROP TABLE \`offer\``);
        await queryRunner.query(`DROP TABLE \`application\``);
        await queryRunner.query(`DROP INDEX \`IDX_15f634a2dbf62a79bb726fc615\` ON \`topic\``);
        await queryRunner.query(`DROP TABLE \`topic\``);
    }

}
